const AUDIT_LEVELS = Object.freeze({
  CRITICAL: "CRITICAL",
  BUSINESS: "BUSINESS",
  OPERATIONAL: "OPERATIONAL",
  TELEMETRY: "TELEMETRY",
});

const RETENTION_CLASSES = Object.freeze({
  FINANCIAL: "FINANCIAL",
  SECURITY: "SECURITY",
  BUSINESS: "BUSINESS",
  OPERATIONAL: "OPERATIONAL",
  TELEMETRY: "TELEMETRY",
});

const RETENTION_DAYS = Object.freeze({
  [RETENTION_CLASSES.FINANCIAL]: 2555,
  [RETENTION_CLASSES.SECURITY]: 730,
  [RETENTION_CLASSES.BUSINESS]: 1825,
  [RETENTION_CLASSES.OPERATIONAL]: 365,
  [RETENTION_CLASSES.TELEMETRY]: 90,
});

const ACTOR_TYPES = Object.freeze({
  USER: "USER",
  PUBLIC: "PUBLIC",
  SYSTEM: "SYSTEM",
  SERVICE: "SERVICE",
  CLI: "CLI",
});

const AUDIT_OUTCOMES = Object.freeze({
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
  DENIED: "DENIED",
  PARTIAL: "PARTIAL",
  NO_OP: "NO_OP",
});

const ENTITY_TYPES = Object.freeze({
  AUTHENTICATION: "AUTHENTICATION",
  USER: "USER",
  STAFF: "STAFF",
  BRANCH: "BRANCH",
  SETTINGS: "SETTINGS",
  ORDER: "ORDER",
  KOT: "KOT",
  BILLING: "BILLING",
  PAYMENT: "PAYMENT",
  INVENTORY: "INVENTORY",
  MENU: "MENU",
  CUSTOMER: "CUSTOMER",
  TABLE: "TABLE",
  SYSTEM: "SYSTEM",
});

const CHANGE_OPERATIONS = Object.freeze({
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  STATUS_TRANSITION: "STATUS_TRANSITION",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
});

const enumValues = (enumeration) => Object.values(enumeration);

module.exports = {
  ACTOR_TYPES,
  AUDIT_LEVELS,
  AUDIT_OUTCOMES,
  CHANGE_OPERATIONS,
  ENTITY_TYPES,
  RETENTION_CLASSES,
  RETENTION_DAYS,
  enumValues,
};
