const AUDIT_ACTIONS = Object.freeze({
  AUTH_SIGNUP: "AUTH.SIGNUP",
  AUTH_LOGIN: "AUTH.LOGIN",
  AUTH_REFRESH: "AUTH.REFRESH",
  AUTH_LOGOUT: "AUTH.LOGOUT",
  AUTH_PASSWORD_CHANGE: "AUTH.PASSWORD_CHANGE",
  AUTH_PROFILE_UPDATE: "AUTH.PROFILE_UPDATE",
  AUTH_ACCESS_DENIED: "AUTH.ACCESS_DENIED",
  AUTH_ACCOUNT_LOCKED: "AUTH.ACCOUNT_LOCKED",

  USER_CREATE: "USER.CREATE",
  USER_ROLE_CHANGE: "USER.ROLE_CHANGE",
  USER_STATUS_CHANGE: "USER.STATUS_CHANGE",
  USER_DELETE: "USER.DELETE",

  STAFF_ASSIGN_BRANCH: "STAFF.ASSIGN_BRANCH",
  STAFF_REMOVE_BRANCH: "STAFF.REMOVE_BRANCH",
  STAFF_CREATE: "STAFF.CREATE",
  STAFF_UPDATE: "STAFF.UPDATE",
  STAFF_DELETE: "STAFF.DELETE",
  STAFF_ROLE_CHANGE: "STAFF.ROLE_CHANGE",
  STAFF_STATUS_CHANGE: "STAFF.STATUS_CHANGE",

  BRANCH_CREATE: "BRANCH.CREATE",
  BRANCH_UPDATE: "BRANCH.UPDATE",
  BRANCH_ACTIVATE: "BRANCH.ACTIVATE",
  BRANCH_DEACTIVATE: "BRANCH.DEACTIVATE",
  BRANCH_DELETE: "BRANCH.DELETE",

  SETTINGS_CREATE: "SETTINGS.CREATE",
  SETTINGS_UPDATE: "SETTINGS.UPDATE",
  SETTINGS_RESET: "SETTINGS.RESET",

  ROLE_ASSIGNMENT: "ROLE_ASSIGNMENT",
  PERMISSION_CHANGE: "PERMISSION_CHANGE",
  ACCOUNT_LOCK: "ACCOUNT_LOCK",
  ACCOUNT_UNLOCK: "ACCOUNT_UNLOCK",

  ORDER_CREATE: "ORDER.CREATE",
  ORDER_SEND_TO_KITCHEN: "ORDER.SEND_TO_KITCHEN",
  ORDER_SEND_TO_CASHIER: "ORDER.SEND_TO_CASHIER",
  ORDER_SERVE: "ORDER.SERVE",
  ORDER_RECEIVE: "ORDER.RECEIVE",
  ORDER_CANCEL: "ORDER.CANCEL",
  ORDER_STATUS_CHANGE: "ORDER.STATUS_CHANGE",

  KOT_CREATE: "KOT.CREATE",
  KOT_START_PREPARATION: "KOT.START_PREPARATION",
  KOT_MARK_READY: "KOT.MARK_READY",
  KOT_SERVE: "KOT.SERVE",
  KOT_CANCEL: "KOT.CANCEL",
  KOT_STATUS_CHANGE: "KOT.STATUS_CHANGE",

  BILLING_CREATE: "BILLING.CREATE",
  BILLING_UPDATE: "BILLING.UPDATE",
  BILLING_DELETE: "BILLING.DELETE",

  PAYMENT_COLLECT: "PAYMENT.COLLECT",
  PAYMENT_FAIL: "PAYMENT.FAIL",
  PAYMENT_VOID: "PAYMENT.VOID",
  PAYMENT_REFUND: "PAYMENT.REFUND",

  INVENTORY_CREATE: "INVENTORY.CREATE",
  INVENTORY_UPDATE: "INVENTORY.UPDATE",
  INVENTORY_RESTOCK: "INVENTORY.RESTOCK",
  INVENTORY_ADJUST: "INVENTORY.ADJUST",
  INVENTORY_DEDUCT: "INVENTORY.DEDUCT",
  INVENTORY_RETURN: "INVENTORY.RETURN",
  INVENTORY_DEACTIVATE: "INVENTORY.DEACTIVATE",

  MENU_CREATE_ITEM: "MENU.CREATE_ITEM",
  MENU_UPDATE_ITEM: "MENU.UPDATE_ITEM",
  MENU_CHANGE_PRICE: "MENU.CHANGE_PRICE",
  MENU_CHANGE_AVAILABILITY: "MENU.CHANGE_AVAILABILITY",
  MENU_DELETE_ITEM: "MENU.DELETE_ITEM",

  CUSTOMER_CREATE: "CUSTOMER.CREATE",
  CUSTOMER_UPDATE: "CUSTOMER.UPDATE",
  CUSTOMER_DELETE: "CUSTOMER.DELETE",

  TABLE_CREATE: "TABLE.CREATE",
  TABLE_UPDATE: "TABLE.UPDATE",
  TABLE_ALLOCATE: "TABLE.ALLOCATE",
  TABLE_FREE: "TABLE.FREE",
  TABLE_CHANGE_STATUS: "TABLE.CHANGE_STATUS",
  TABLE_DELETE: "TABLE.DELETE",

  SYSTEM_SEED_START: "SYSTEM.SEED_START",
  SYSTEM_SEED_COMPLETE: "SYSTEM.SEED_COMPLETE",
  SYSTEM_SEED_FAIL: "SYSTEM.SEED_FAIL",
  SYSTEM_AUDIT_SEARCH: "SYSTEM.AUDIT_SEARCH",
  SYSTEM_AUDIT_EXPORT: "SYSTEM.AUDIT_EXPORT",
  SYSTEM_ARCHIVE: "SYSTEM.ARCHIVE",
  SYSTEM_RETENTION_PURGE: "SYSTEM.RETENTION_PURGE",
  SYSTEM_CONFIG_CHANGE: "SYSTEM.CONFIG_CHANGE",
});

const AUDIT_ACTION_VALUES = Object.freeze(Object.values(AUDIT_ACTIONS));

module.exports = { AUDIT_ACTIONS, AUDIT_ACTION_VALUES };
